import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, AlertTriangle, Gauge, Router, ShieldCheck, Plus, RefreshCcw, HardDriveDownload} from 'lucide-react';
import './style.css';

const api=(path, opts={})=>fetch('/api'+path,{headers:{'Content-Type':'application/json', ...(localStorage.token?{Authorization:`Bearer ${localStorage.token}`}:{})},...opts}).then(async r=>{const j=await r.json(); if(!r.ok) throw new Error(j.detail||'Request failed'); return j});

function Login({onLogin}){const [mode,setMode]=useState('login'); const [username,setUsername]=useState('admin'); const [password,setPassword]=useState(''); const [err,setErr]=useState('');
 const submit=async e=>{e.preventDefault();setErr('');try{const x=await api('/auth/'+mode,{method:'POST',body:JSON.stringify({username,password})});localStorage.token=x.access_token;onLogin();}catch(e){setErr(e.message)}};
 return <div className="login"><div className="login-card"><div className="brand">NetHealth <span>Community</span></div><p className="muted">On-premise MikroTik monitoring</p><form onSubmit={submit}><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Username"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><button>{mode==='login'?'Sign in':'Create admin'}</button></form>{err&&<div className="error">{err}</div>}<button className="link" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'First run? Create admin':'Back to login'}</button></div></div>}

function App(){const [auth,setAuth]=useState(!!localStorage.token); return auth?<Dashboard logout={()=>{localStorage.removeItem('token');setAuth(false)}}/>:<Login onLogin={()=>setAuth(true)}/>}

function Dashboard({logout}){const [summary,setSummary]=useState(null),[devices,setDevices]=useState([]),[alerts,setAlerts]=useState([]),[open,setOpen]=useState(false),[form,setForm]=useState({name:'MikroTik-01',ip:'192.168.88.1',username:'monitor',password:'',port:443,use_ssl:true}),[msg,setMsg]=useState('');
 const load=async()=>{try{const [s,d,a]=await Promise.all([api('/devices/summary'),api('/devices'),api('/devices/alerts')]);setSummary(s);setDevices(d);setAlerts(a)}catch(e){setMsg(e.message)}}; useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]);
 const add=async e=>{e.preventDefault();try{await api('/devices',{method:'POST',body:JSON.stringify(form)});setOpen(false);setForm({...form,password:''});setMsg('Router added');load()}catch(e){setMsg(e.message)}};
 const monitor=async id=>{await api('/devices/'+id+'/monitor',{method:'POST'});load()}; const backup=async id=>{await api('/devices/'+id+'/backup',{method:'POST'});setMsg('Config export saved')};
 if(!summary)return <div className="splash">Loading…</div>;
 return <div className="app"><aside><div className="brand">NetHealth <span>Community</span></div><nav><a className="active">Overview</a><a>Devices</a><a>Alerts</a><a>Discovery</a><a>Backups</a></nav><button className="logout" onClick={logout}>Sign out</button></aside><main><header><div><h1>Network Overview</h1><p className="muted">Community Edition · MikroTik focus · single-device limit</p></div><div className="actions"><button className="ghost" onClick={load}><RefreshCcw size={17}/>Refresh</button><button onClick={()=>setOpen(true)}><Plus size={17}/>Add MikroTik</button></div></header>
 <section className="grid stats"><Card icon={<Gauge/>} title="Network Health" value={`${summary.network_health}%`} tone={summary.network_health<70?'bad':'good'}/><Card icon={<Router/>} title="Devices" value={`${summary.online}/${summary.devices}`} tone="neutral"/><Card icon={<AlertTriangle/>} title="Critical Alerts" value={summary.critical} tone={summary.critical?'bad':'good'}/><Card icon={<Activity/>} title="Warnings" value={summary.warning} tone={summary.warning?'warn':'good'}/></section>
 <section className="panel"><div className="panel-head"><h2>Devices</h2><span className="muted">Polling every 30s</span></div><div className="table">{devices.map(d=><div className="row" key={d.id}><div><strong>{d.name}</strong><div className="muted">{d.ip} · {d.model||'MikroTik'}</div></div><Status s={d.status}/><div className="health"><span style={{width:`${d.health}%`}}></span></div><strong>{d.health}%</strong><div className="row-actions"><button className="tiny ghost" onClick={()=>monitor(d.id)} title="Monitor"><RefreshCcw size={14}/></button><button className="tiny ghost" onClick={()=>backup(d.id)} title="Backup"><HardDriveDownload size={14}/></button></div></div>)}{!devices.length&&<div className="empty">No device yet. Add your MikroTik router.</div>}</div></section>
 <section className="grid two"><section className="panel"><div className="panel-head"><h2>Active Alerts</h2></div>{alerts.filter(a=>a.active).slice(0,8).map(a=><div className="alert" key={a.id}><AlertTriangle size={18}/><div><strong>{a.title}</strong><div className="muted">{a.message}</div></div><span className={a.severity}>{a.severity}</span></div>)}{!alerts.filter(a=>a.active).length&&<div className="empty">No active alerts.</div>}</section><section className="panel"><div className="panel-head"><h2>Community scope</h2></div><div className="feature"><ShieldCheck size={20}/><div><strong>Included</strong><div className="muted">CPU, RAM, uptime, interface snapshot, ICMP latency/loss, basic routes, DHCP pool data, basic alerts and .rsc export.</div></div></div><div className="feature"><Router size={20}/><div><strong>Designed for extension</strong><div className="muted">Provider abstraction keeps future Cisco, FortiGate, Huawei and generic SNMP integrations out of the core.</div></div></div></section></section>
 {open&&<div className="modal"><form className="modal-card" onSubmit={add}><h2>Add MikroTik</h2><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Name"/><input value={form.ip} onChange={e=>setForm({...form,ip:e.target.value})} placeholder="IP"/><input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} placeholder="RouterOS username"/><input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="RouterOS password"/><div className="inline"><input type="number" value={form.port} onChange={e=>setForm({...form,port:Number(e.target.value)})}/><label><input type="checkbox" checked={form.use_ssl} onChange={e=>setForm({...form,use_ssl:e.target.checked})}/> HTTPS REST</label></div><div className="modal-actions"><button type="button" className="ghost" onClick={()=>setOpen(false)}>Cancel</button><button>Add & Test</button></div></form></div>}
 {msg&&<div className="toast" onClick={()=>setMsg('')}>{msg}</div>}
 </main></div>}

const Card=({icon,title,value,tone})=><div className="card"><div className="icon">{icon}</div><div><div className="muted">{title}</div><div className={`value ${tone}`}>{value}</div></div></div>;
const Status=({s})=><span className={`status ${s==='online'?'online':'offline'}`}><i></i>{s}</span>;

createRoot(document.getElementById('root')).render(<App/>);
